name: Build and Deploy Analysis Site

on:
  push:
    branches:
      - develop # This workflow runs when you push to the 'develop' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the action to push to the deployment branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Or your preferred version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas numpy scikit-learn plotly

      - name: Run Notebook to Generate HTML Files
        run: |
          # This command's only job is to RUN your notebook. 
          # The Python code inside your notebook is what creates the `analysis` folder
          # and saves the interactive .html files.
          jupyter nbconvert --to notebook --execute "Model and Visuals.ipynb" --output "index.html"

      - name: Prepare Files for Publishing
        run: |
          # Copy the source notebook and data files into the analysis folder
          # so they are also included in the deployment.
          cp "Model and Visuals.ipynb" analysis/
          cp *.csv analysis/

      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch to deploy TO (e.g., main or gh-pages)
          FOLDER: analysis # The folder to deploy FROM
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}